In [1]:
import radar_attenuation.gaia_util as gu
import radar_attenuation.gaia_eutectic_util as geu

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
gaia_temp_table = np.loadtxt("../data/gaia/temp_profile/europa/test_one/thermochemical_40km_Drho46_2D_data.txt", comments= "#")

In [3]:
gaia_temp_table

array([[ 1.52079981e+03, -1.23455647e-01,  0.00000000e+00,
         2.69224000e+02,  7.50000000e-01],
       [ 1.52079981e+03,  1.23455647e-01,  0.00000000e+00,
         2.69224000e+02,  7.50000000e-01],
       [ 1.52079977e+03,  3.70366937e-01,  0.00000000e+00,
         2.69224000e+02,  7.50000000e-01],
       ...,
       [ 1.54854022e+03,  1.95242994e+02,  0.00000000e+00,
         1.10000000e+02,  7.50000000e+00],
       [ 1.54850850e+03,  1.95494407e+02,  0.00000000e+00,
         1.10000000e+02,  7.50000000e+00],
       [ 1.54847674e+03,  1.95745814e+02,  0.00000000e+00,
         1.10000000e+02,  7.50000000e+00]])

In [4]:
gaia_temp_table.shape

(125712, 5)

In [5]:
x = gaia_temp_table[:, 0]
y = gaia_temp_table[:, 1]
z = gaia_temp_table[:, 2]

radius_array = np.round(np.sqrt(x**2 + y**2 + z**2)*1000, 3)
RO = np.min(radius_array)

radius_array = radius_array - RO
radius_array

array([    0.   ,     0.   ,     0.   , ..., 40000.182, 40000.182,
       40000.182])

In [6]:
np.unique(radius_array).shape[0]

162

In [7]:
# I would expect the counts to be equal, that is there are an equal number of cells for every shell, 
# where each shell is denoted by a unique radius value, but that does not seem to be the case. 
# there are anywhere from 1 to 611 instances where np.sqrt(x**2 + y**2 + z**2) = a unique radius value
# 611 is not the number of cells per shell
unique_array = np.unique(radius_array, return_counts=True)

print(np.max(unique_array[1]))
print(np.min(unique_array[1]))

unique_array

776
776


(array([    0.   ,   125.   ,   375.001,   625.002,   875.004,  1125.005,
         1375.006,  1625.007,  1875.008,  2125.009,  2375.01 ,  2625.012,
         2875.013,  3125.014,  3375.015,  3625.016,  3875.017,  4125.018,
         4375.02 ,  4625.021,  4875.022,  5125.023,  5375.024,  5625.025,
         5875.026,  6125.028,  6375.029,  6625.03 ,  6875.031,  7125.032,
         7375.033,  7625.034,  7875.036,  8125.037,  8375.038,  8625.039,
         8875.04 ,  9125.041,  9375.042,  9625.043,  9875.045, 10125.046,
        10375.047, 10625.048, 10875.049, 11125.05 , 11375.051, 11625.053,
        11875.054, 12125.055, 12375.056, 12625.057, 12875.058, 13125.059,
        13375.061, 13625.062, 13875.063, 14125.064, 14375.065, 14625.066,
        14875.067, 15125.069, 15375.07 , 15625.071, 15875.072, 16125.073,
        16375.074, 16625.075, 16875.077, 17125.078, 17375.079, 17625.08 ,
        17875.081, 18125.082, 18375.083, 18625.085, 18875.086, 19125.087,
        19375.088, 19625.089, 19875.09

In [8]:
unique_array[1][:16]

array([776, 776, 776, 776, 776, 776, 776, 776, 776, 776, 776, 776, 776,
       776, 776, 776])

In [9]:
print(np.sum(unique_array[1][:5])) # 5
print(np.sum(unique_array[1][5:8])) # 4
print(np.sum(unique_array[1][8:12])) # 4
print(np.sum(unique_array[1][12:16])) # 4

3880
2328
3104
3104


In [17]:
caseID = 'BasalG1_Ann'
path_to_caseID = "../data/gaia/temp_profile/europa/test_one/"

return_list = gu.load_sim(caseID, path_to_caseID, -1)
s_1e3 = return_list[0]
o_1e3 = return_list[1]
nShells = o_1e3.grid.nShells
nCellsPerShell = o_1e3.grid.nCellsPerShell[0]
print(nCellsPerShell)




Case: BasalG1_Ann Loaded Grid: BasalG1_Ann.grid
Got 0 new files, 1 in total.
Loaded time 0.26848397042127975 and iteration 79027
cells per depth 776.0
776


In [ ]:
o_1e3.T.data.shape

(125712, 1)